4주차 데모 배포 버그 수정 사항 - auth 로직, 서재 수정모드
boostcampwm-2022/web01-knoticle pull request #213
Opened 2022-12-06 08:20 UTC by MinHK4

## 개요

4주차 데모 발표 후 피어세션, 유저 피드백에서 나온 버그 사항들 확인 및 수정

## 변경 사항

- 로컬 및 깃헙 회원가입 시 책 무조건 하나 생성 
- github 로그인 거절 시 페이지에 계속 남아있게 되는 오류 
- 서재페이지 닉네임 수정 시 빈 닉네임 방지
- 수정 모드에서 수정 완료 토스트 메시지 여러번 노출 오류

## 참고 사항

- 여러 버그들을 수정하고 있어서 커밋 단위로 리뷰하시는게 편하실 수 있을 것 같습니다 : )
- `authService`에서 로컬 및 깃헙 회원가입 부분에 `booksService.createBook`하는 부분이 있습니다. 백엔드 계층 구분에 위배되지 않는지 확인바랍니다.
-  생각해보니 robots.txt에서 `/github` 요기 페이지도 빼줘야 하지 않을까 싶습니다
- 공백 닉네임 방지 UI부분은 없어서 기존 다른 부분의 관행에 맞춰서 진행했습니다.
- 수정 모드에서 useFetch를 사용하는 과정에서 해당 수정 모드에서 완료된 삭제 혹은 수정 작업을 구분하기 위해서 초기의 undefined 값을 설정해놓을 필요가 있었고 이를 위해서 useFetch에서 setData를 받아서 쓰고 있습니다. 객체로 뺴주다보니 다른 코드에 영향은 없으나 혹시 사용 방식에 대한 이해가 다른가 싶어 남깁니다.

## 스크린샷
![image](https://user-images.githubusercontent.com/67371123/205856189-cdc9fae1-9a62-40ca-aab3-7c8dfd211a55.png)

## 관련 이슈

- closes #194 
- closes #195 
- closes #208 
- closes #209

2022-12-06 17:07 UTC, doputer requested changes
any와의 전쟁을 선포하셨군요...!

2022-12-06 17:07 UTC, doputer commented on frontend/components/study/FAB/index.tsx
> +      if (editInfo.deleted.length === 0 && editInfo.editted.length === 0)
수정이나 삭제가 일어나지 않았을 때 후 처리를 해주는 과정일까요?

사실 useFetch 훅을 수정해서 데이터 패칭해 온 것을 undefined로 만들어줘야되는 이유가 잘 이해되지 않습니다. 내일 조금 더 자세하게 설명해주실 수 있을까요?

공통으로 사용하는 훅이 수정된 것이지만 내부 로직이 변경된 것이 아니라 다른 부분에서 문제될 사항은 아닌 것 같습니다만, 훅을 수정하지 않고 해결할 수 있는 문제라면 같이 고민해보면 좋을 것 같습니다.

2022-12-07 01:11 UTC, parkhyeonki reviewed
어제 말씀해주신 저의 any와 IEditscrap 부분은 오늘 머지하면서 충돌만 해결하고, 남은 부분은 제가 수정하겠습니다!!
다른 부분은 도현님이 잘 남겨주셔서 저도 오늘 데일리스크럼때 같이 들어보면 될 것 같아요!

2022-12-07 02:07 UTC, MinHK4 commented on backend/src/apis/auth/auth.service.ts
> +
오 레퍼런스까지 보니까 이해가 확실히 되네요!! 피드백 감사합니다 : )

2022-12-07 05:32 UTC, parkhyeonki approved these changes

2022-12-07 05:32 UTC, merged